"set exrc
set encoding=utf-8
set smarttab
set showmode
set tw=72
set hlsearch
set ignorecase

set expandtab
set cinoptions=p0,t0,+4,(0,u4,U1,:0
set formatoptions=tcroq
set comments=sr:/*,mb:*,ex:*/,://

set secure
set autoindent
set shiftwidth=4
set softtabstop=4
set noexpandtab
set tabstop=4
set incsearch
vnoremap // y/<C-R>"<CR>

" 접근했을때 마지막으로 수정한 곳에서 커서를 위치합니다.
au BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "norm g`\"" |
\ endif

" set the runtime path to include Vundle and initialize
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set nocompatible              " be iMproved, required
filetype off                  " required

"set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/.vim/bundle/vundle
call vundle#begin()            " required
Plugin 'VundleVim/Vundle.vim'
Plugin 'L9', {'name': 'newL9'}
Plugin 'ctrlp.vim'
Plugin 'fugitive.vim'
Plugin 'Gundo'
Plugin 'NERD_tree-Project'
Plugin 'The-NERD-tree'
Plugin 'highlight.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'Syntastic'
Plugin 'EasyMotion'
Plugin 'Command-T'
Plugin 'dracula/vim',{'name': 'dracula'}
" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required

syntax on
color dracula

" for vim-airline
" let g:airline#extensions#tabline#enabled = 1 " turn on buffer list
let g:airline_solarized_bg='dark'
let g:airline_theme='luna'
set laststatus=2 " turn on bottom bar

" for NERDTree
map <F2> :NERDTreeToggle<CR>
map <F4> :GundoToggle<CR>
" Press F3 to toggle highlighting on/off, and show current value.
noremap <F3> :set hlsearch! hlsearch?<CR>

" for c-support
let g:C_UseTool_cmake    = 'yes'
let g:C_UseTool_doxygen  = 'yes'

" end-of-file
